apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bench-results
  namespace: rag-bench-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-zcp
  resources:
    requests:
      storage: 10Gi
